module.exports = Object.freeze({
    RISK_EVAL_CREATED: 'mga_riskeval_created',
    KYC_START: 'mga_kyc_start',
    CREDIT_RATING_START: 'mga_credit_rating_start',
    ASSET_VALIDATION_START: 'mga_asset_validation_start',
    COVERAGE_VALIDATION_START: 'mga_coverage_validation_start',
    KYC_COMPLETED: 'mga_kyc_completed',
    ASSET_VALIDATION_COMPLETED: 'mga_asset_validation_completed',
    COVERAGE_VALIDATION_COMPLETED: 'mga_coverage_validation_completed',
    CREDIT_RATING_COMPLETED: 'mga_credit_rating_completed',
    RISK_SCORING_COMPLETED: 'mga_flood_risk_scoring_completed',
    RISK_PRICING_COMPLETED: 'mga_flood_risk_pricing_completed',
    COMPLETED: 'completed',
    QUOTE_CREATED: 'mga_quote_created',
    QUOTE_REQUEST_COMPLETED: 'mga_quote_request_completed',
    QUOTE_SUBMIT_START: 'mga_quote_submit_start',
    QUOTE_SUBMIT_COMPLETED: 'mga_quote_submit_completed',
    QUOTE_ACCEPT_START: 'mga_quote_accept_start',
    QUOTE_REJECT_START: 'mga_quote_reject_start',
    QUOTE_ACCEPT_COMPLETED: 'mga_quote_accept_completed',
    QUOTE_REJECT_COMPLETED: 'mga_quote_reject_completed',
    PARTY: {
        INSURANCE_PROVIDER: 'INSURANCE_PROVIDER',
        INSURANCE_DISTRIBUTOR: 'INSURANCE_DISTRIBUTOR',
        INSURANCE_BROKER: 'INSURANCE_BROKER',
        INSURANCE_MGA: 'INSURANCE_MGA',
        INSURANCE_INSURED: 'INSURANCE_INSURED',
        INSURANCE_REGULATOR: 'INSURANCE_REGULATOR',
        INSURANCE_PARTNER: 'INSURANCE_PARTNER',
        INSURANCE_AGENCY: 'INSURANCE_AGENCY',  
        INSURANCE_PAYOR: 'INSURANCE_PAYOR', 
        INSURANCE_ASSOCIATION: 'INSURANCE_ASSOCIATION', 
        INSURANCE_PLATFORM_ADMIN: 'INSURANCE_PLATFORM_ADMIN',
        INSURANCE_CARRIER: 'INSURANCE_CARRIER'
    }
});