service: mga-riskeval
frameworkVersion: '3'

custom:
  tableNameRiskOrchestrator: 'mga_risk_orchestrator_table'
  tableNameKyc: 'mga_kyc_table'
  tableNameCreditRating: 'mga_credit_rating_table'
  tableNameAssetValidation: 'mga_asset_validation_table'
  tableNameCoverageValidation: 'mga_coverage_validation_table'
  tableNameFloodRiskScoring: 'mga_flood_risk_scoring_table'
  tableNameFloodRiskPricing: 'mga_flood_risk_pricing_table'
  tableNameQuoteOrchestrator: 'mga_quote_orchestrator_table'
  tableNameQuoteRequest: 'mga_quote_request_table'
  tableNameQuoteSubmit: 'mga_quote_submit_table'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ RiskOrchestratorTable, Arn ]
            - Fn::GetAtt: [ KycTable, Arn ]
            - Fn::GetAtt: [ CreditRatingTable, Arn ]
            - Fn::GetAtt: [ AssetValidationTable, Arn ]
            - Fn::GetAtt: [ CoverageValidationTable, Arn ]
            - Fn::GetAtt: [ FloodRiskScoringTable, Arn ]
            - Fn::GetAtt: [ FloodRiskPricingTable, Arn ]
            - Fn::GetAtt: [ QuoteOrchestratorTable, Arn ]
            - Fn::GetAtt: [ QuoteRequestTable, Arn ]
            - Fn::GetAtt: [ QuoteSubmitTable, Arn ]

        - Effect: "Allow"
          Resource: "*"
          Action:
            - "sns:*"

  environment:
    ACCOUNT_ID: ${aws:accountId}
    REGION: ${self:provider.region}
    RISK_ORCHESTRATOR_TABLE: ${self:custom.tableNameRiskOrchestrator}
    KYC_TABLE: ${self:custom.tableNameKyc}
    CREDIT_RATING_TABLE: ${self:custom.tableNameCreditRating}
    ASSET_VALIDATION_TABLE: ${self:custom.tableNameAssetValidation}
    COVERAGE_VALIDATION_TABLE: ${self:custom.tableNameCoverageValidation}
    FLOOD_RISK_SCORING_TABLE: ${self:custom.tableNameFloodRiskScoring}
    FLOOD_RISK_PRICING_TABLE: ${self:custom.tableNameFloodRiskPricing}
    QUOTE_ORCHESTRATOR_TABLE: ${self:custom.tableNameQuoteOrchestrator}
    QUOTE_REQUEST_TABLE: ${self:custom.tableNameQuoteRequest}
    QUOTE_SUBMIT_TABLE: ${self:custom.tableNameQuoteSubmit}
    PRODUCT_API_URL: 'https://lf99je7gbk.execute-api.us-west-2.amazonaws.com/product/'
    CARRIER_API_URL: 'https://e4owmidsn2.execute-api.us-west-2.amazonaws.com'

functions:
  core_api_fn:
    handler: functions/core_services/core_api_fn.core_api
    events:
      - httpApi: '*'
  kyc_fn:
    handler: functions/add_on_services/kyc_fn.kyc
    events:
      - sns: mga_kyc_start
  credit_rating_fn:
    handler: functions/add_on_services/credit_rating_fn.credit_rating
    events:
      - sns: mga_credit_rating_start
  asset_validation_fn:
    handler: functions/add_on_services/asset_validation_fn.asset_validation
    events:
      - sns: mga_asset_validation_start
  coverage_validation_fn:
    handler: functions/add_on_services/coverage_validation_fn.coverage_validation
    events:
      - sns: mga_coverage_validation_start
  flood_risk_scoring_fn:
    handler: functions/risk/flood_risk/flood_risk_scoring_fn.risk_scoring
    events:
      - sns: mga_flood_risk_scoring_start
  flood_risk_pricing_fn:
    handler: functions/risk/flood_risk/flood_risk_pricing_fn.risk_pricing
    events:
      - sns: mga_flood_risk_pricing_start
  risk_orchestrator_fn:
    handler: functions/core_services/risk_eval/risk_orchestrator_fn.orchestrator
    events:
      - sns: mga_riskeval_created
      - sns: mga_kyc_completed
      - sns: mga_asset_validation_completed
      - sns: mga_coverage_validation_completed
      - sns: mga_credit_rating_completed
      - sns: mga_flood_risk_scoring_completed
      - sns: mga_flood_risk_pricing_completed
  quote_orchestrator_fn:
    handler: functions/core_services/quote/quote_orchestrator_fn.orchestrator
    events:
      - sns: mga_quote_created
      - sns: mga_quote_request_completed
      - sns: mga_quote_submit_completed
      - sns: mga_quote_accept_completed
      - sns: mga_quote_reject_completed
      - sns: mga_kyc_completed
      - sns: mga_asset_validation_completed
      - sns: mga_coverage_validation_completed
      - sns: mga_credit_rating_completed
      - sns: mga_flood_risk_scoring_completed
      - sns: mga_flood_risk_pricing_completed
  quote_request_fn:
    handler: functions/add_on_services/quote_request_fn.request
    events:
      - sns: mga_quote_request_start
  quote_submit_fn:
    handler: functions/add_on_services/quote_submit_fn.submit
    events:
      - sns: mga_quote_submit_start
  quote_accept_fn:
    handler: functions/add_on_services/quote_accept_fn.accept
    events:
      - sns: mga_quote_accept_start
  quote_reject_fn:
    handler: functions/add_on_services/quote_reject_fn.reject
    events:
      - sns: mga_quote_reject_start

resources:
  Resources:
    RiskOrchestratorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameRiskOrchestrator}
    KycTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameKyc}
    CreditRatingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameCreditRating}
    AssetValidationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameAssetValidation}
    CoverageValidationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameCoverageValidation}
    FloodRiskScoringTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameFloodRiskScoring}
    FloodRiskPricingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameFloodRiskPricing}
    QuoteOrchestratorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: quote_request_id
            AttributeType: S
        KeySchema:
          - AttributeName: quote_request_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameQuoteOrchestrator}
    QuoteRequestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: quote_request_id
            AttributeType: S
        KeySchema:
          - AttributeName: quote_request_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameQuoteRequest}
    QuoteSubmitTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: quote_id
            AttributeType: S
        KeySchema:
          - AttributeName: quote_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameQuoteSubmit}